### ISSUE TITLE
Where are descriptors?

### ISSUE THREAD

**Issue by carpovpv** [ncats/ld50-multitask#1]
Hi!

It seems like data files have to contain descriptors (rdkit, fp, pairs, etc.). Where are they? Or where is the code that calculates them? I cannot run you code because of that. 

Thanks.

**Comment by iwwwish** [comment]
Hi @carpovpv 

We have the descriptors (Avalon fingerprint bits) in a separate file. There's a [notebook](https://github.com/ncats/ld50-multitask/blob/master/notebooks/create_fold_data.ipynb) in our repository that provides an example of how one can combine the data set with descriptors to create fold data for training the models.

Hope this helps.

Best,
Vishal

**Comment by carpovpv** [comment]
Hi!

I'm asking about other descriptors (rdkit, fp, pairs). The separate file you are talking about contains only Avalon data. 
Where are these guys?

X_train1 = dataset.iloc[:,1204:2228].values # morgan fp
X_train2 = dataset.iloc[:,180:1204].values # avalon fp
X_train3 = dataset.iloc[:,2228:3252].values # atom pair fp
X_train4 = dataset.iloc[:,61:180].values # rdkit desc

Thanks.

**Comment by iwwwish** [comment]
The compound structures are provided as SMILES, using which others descriptors can always be calculated. Our initial idea was to provide an example using Avalon bits. However, for your convenience, we made all descriptors available in a [single file](https://github.com/ncats/ld50-multitask/blob/master/data/all_descriptors.csv). The procedure to combine descriptors with the data set remains the same though.

Best,
Vishal
